// import { IPerson } from "../interfaces/interfaces";

// export const personsList: IPerson[] = [
export const personsList = [
  {
    id: 12,
    name: 'Nezařazený',
    phone: 0,
    status: { zamestnanec: [], student: [] },
    unit: [],
    favourite: false,
    myId: 1200,
  },
  {
    id: 13,
    name: 'Nezařazený',
    phone: 111111111,
    status: { zamestnanec: [], student: [] },
    unit: [],
    favourite: true,
    myId: 1300,
  },
  {
    id: 1,
    name: 'Jules Verne',
    phone: 111111111,
    status: { zamestnanec: ['ÚVT'], student: ['FI', 'FF'] },
    unit: ['ÚVT', 'FI', 'FF'],
    favourite: true,
    myId: 100,
  },
  {
    id: 2,
    name: 'Ota Pavel',
    phone: 222222222,
    status: { zamestnanec: ['PřF'], student: [] },
    unit: ['PřF'],
    favourite: true,
    myId: 200,
  },
  {
    id: 3,
    name: 'Bohumil Hrabal',
    phone: 333333333,
    status: { zamestnanec: [], student: ['ESF'] },
    unit: ['ESF'],
    favourite: true,
    myId: 300,
  },
  {
    id: 4,
    name: 'Jan Skácel',
    phone: 444444444,
    status: { zamestnanec: ['PrF'], student: [] },
    unit: ['PrF'],
    favourite: false,
    myId: 400,
  },
  {
    id: 5,
    name: 'Karel Čapek',
    phone: 555555555,
    status: { zamestnanec: ['FF'], student: ['FF'] },
    unit: ['FF'],
    favourite: false,
    myId: 500,
  },
  {
    id: 6,
    name: 'Arnošt Lustig',
    phone: 666666666,
    status: { zamestnanec: ['FSS'], student: ['FSS'] },
    unit: ['FSS'],
    favourite: false,
    myId: 600,
  },
  {
    id: 7,
    name: 'Vladislav Vančura',
    phone: 777777777,
    status: { zamestnanec: ['FI'], student: [] },
    unit: ['FI'],
    favourite: false,
    myId: 700,
  },
  {
    id: 8,
    name: 'Karolina Světlá',
    phone: 888888888,
    status: { zamestnanec: ['PdF'], student: [] },
    unit: ['PdF'],
    favourite: false,
    myId: 800,
  },
  {
    id: 9,
    name: 'Alena Mornštajnová',
    phone: 999999999,
    status: { zamestnanec: ['FSpS'], student: [] },
    unit: ['FSpS'],
    favourite: false,
    myId: 900,
  },
  {
    id: 10,
    name: 'Božena Němcová',
    phone: 111222333,
    status: { zamestnanec: ['CEITEC'], student: [] },
    unit: ['CEITEC'],
    favourite: false,
    myId: 1000,
  },
  {
    id: 11,
    name: 'Zdeněk Machač',
    phone: 22222111,
    status: { zamestnanec: ['ÚVT'], student: [] },
    unit: ['FI'],
    favourite: true,
    myId: 1100,
  },
  {
    id: 14,
    name: 'Nezařazený',
    phone: 222222222,
    status: { zamestnanec: [], student: [] },
    unit: [],
    favourite: true,
    myId: 1400,
  },
  {
    id: 15,
    name: 'Nezařazený',
    phone: 333333333,
    status: { zamestnanec: [], student: [] },
    unit: [],
    favourite: true,
    myId: 1500,
  },
  {
    id: 16,
    name: 'Nezařazený',
    phone: 444444444,
    status: { zamestnanec: [], student: [] },
    unit: [],
    favourite: false,
    myId: 1600,
  },
  {
    id: 17,
    name: 'Nezařazený',
    phone: 555555555,
    status: { zamestnanec: [], student: [] },
    unit: [],
    favourite: false,
    myId: 1700,
  },
  {
    id: 18,
    name: 'Nezařazený',
    phone: 666666666,
    status: { zamestnanec: [], student: [] },
    unit: [],
    favourite: false,
    myId: 1800,
  },
  {
    id: 19,
    name: 'Nezařazený',
    phone: 777777777,
    status: { zamestnanec: [], student: [] },
    unit: [],
    favourite: false,
    myId: 1900,
  },
  {
    id: 20,
    name: 'Nezařazený',
    phone: 888888888,
    status: { zamestnanec: [], student: [] },
    unit: [],
    favourite: false,
    myId: 2000,
  },
  {
    id: 21,
    name: 'Nezařazený',
    phone: 999999999,
    status: { zamestnanec: [], student: [] },
    unit: [],
    favourite: false,
    myId: 2100,
  },
  {
    id: 22,
    name: 'Nezařazený',
    phone: 111222333,
    status: { zamestnanec: [], student: [] },
    unit: [],
    favourite: false,
    myId: 2200,
  },
]
